Roll_for_Initiative/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("partidas/", include("partidas.urls")),
    path("", RedirectView.as_view(url="/partidas/", permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partidas/urls.py
from django.urls import path

from .views import (
    home_view,
    JuegoListView,
    JuegoDetailView,
    JuegoDeleteView,
    JuegoUpdateView,
    JuegoCreateView,
    juego_search_view,
    SistemaListView,
    SistemaDetailView,
    SistemaUpdateView,
    SistemaDeleteView,
    SistemaCreateView,
    sistema_search_view,
    ReservaListView,
    ReservaDetailView,
    ReservaUpdateView,
    ReservaDeleteView,
    ReservaCreateView,
    user_login_view,
    user_logout_view,
    UserUpdateView,
    user_creation_view,
    avatar_view,
    about_view,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("about/", about_view, name="about"),
    path("juego/list/", JuegoListView.as_view(), name="juego-list"),
    path("juego/create/", JuegoCreateView.as_view(), name="juego-create"),
    path("juego/<int:pk>/detail/", JuegoDetailView.as_view(), name="juego-detail"),
    path("juego/<int:pk>/update/", JuegoUpdateView.as_view(), name="juego-update"),
    path("juego/<int:pk>/delete/", JuegoDeleteView.as_view(), name="juego-delete"),
    path("juego/search/", juego_search_view, name="juego-search"),
    path("sistema/list/", SistemaListView.as_view(), name="sistema-list"),
    path("sistema/create/", SistemaCreateView.as_view(), name="sistema-create"),
    path("sistema/<int:pk>/detail/", SistemaDetailView.as_view(), name="sistema-detail"),
    path("sistema/<int:pk>/update/", SistemaUpdateView.as_view(), name="sistema-update"),
    path("sistema/<int:pk>/delete/", SistemaDeleteView.as_view(), name="sistema-delete"),
    path("sistema/search/", sistema_search_view, name="sistema-search"),
    path("reserva/list/", ReservaListView.as_view(), name="reserva-list"),
    path("reserva/create/", ReservaCreateView.as_view(), name="reserva-create"),
    path("reserva/<int:pk>/detail/", ReservaDetailView.as_view(), name="reserva-detail"),
    path("reserva/<int:pk>/update/", ReservaUpdateView.as_view(), name="reserva-update"),
    path("reserva/<int:pk>/delete/", ReservaDeleteView.as_view(), name="reserva-delete"),
    path("login/", user_login_view, name='login'),
    path("logout/", user_logout_view, name='logout'),
    path("editar-perfil/", UserUpdateView.as_view(), name='editar-perfil'),
    path("crear-usuario/", user_creation_view, name='crear-usuario'),
    path("avatar/add", avatar_view, name="avatar-add"),
]

partidas/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Dado(models.TextChoices):
    D6 = "d6", ("Dado D6")
    D8 = "d8", ("Dado D8")
    D10 = "d10", ("Dado D10")
    D12 = "d12", ("Dado D12")
    D20 = "d20", ("Dado D20")
    MULTIPLE = "multi", ("Diversos dados")

class Base(models.TextChoices):
    DND5E = "dnd5e", ("Dungeons & Dragons 5ª Edición")
    DND3E = "dnd3e", ("Dungeons & Dragons 3ª Edición")
    FF3E = "ff3e", ("Final Fantasy 3ª Edición")
    WHFANTASY = "whf", ("Warhammer Fantasy Roleplay")
    WH40K = "wh40k", ("Warhammer 40.000 Roleplay")
    MARVEL_MV_RPG = "marvel", ("Marvel Multiverse Role-Playing Game")
    PATHFINDER = "path", ("Pathfinder 2ª Edición")
    CTHULHU = "cthul", ("Call of Cthulhu")
    CINCO_ANILLOS = "5ring", ("La Leyenda de los Cinco Anillos")

class Sistema(models.Model):
    nombre = models.CharField(max_length=100)
    dado = models.CharField(
        max_length=6,
        choices=Dado.choices,
        default=Dado.D20
        )
    base = models.CharField(
        max_length=6,
        choices=Base.choices,
        default=Base.DND5E
        )
    descripcion = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.nombre}"

class Juego(models.Model):
    nombre = models.CharField(max_length=250)
    disponible = models.BooleanField(default=True)
    numero_de_jugadores = models.IntegerField()
    sistema_de_juego = models.ForeignKey(Sistema, on_delete=models.CASCADE, related_name='sistema_de_juego')
    descripcion = models.TextField(blank=True, null=True)
    fecha = models.DateField(default=timezone.now)
    hora_inicio = models.TimeField(default=timezone.now().replace(second=0, microsecond=0))
    hora_fin = models.TimeField(default=timezone.now().replace(second=0, microsecond=0))

    def __str__(self):
        return f"{self.nombre}"

class Reserva(models.Model):
    jugador = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    juego = models.ForeignKey(Juego, on_delete=models.CASCADE, related_name='reservas')
    raza = models.CharField(max_length=50)
    clase = models.CharField(max_length=50)
    experiencia = models.BooleanField(default=True)
    descripcion = models.TextField(max_length=500)

    def get_experiencia_display(self):
        return "Si" if self.experiencia else "No"

    def __str__(self):
        return f"¡{self.jugador} se ha unido a {self.juego}!"

class Avatar(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="avatar")
    image = models.ImageField(upload_to="avatars/")

    def __str__(self):
        return f"Avatar de {self.user.username}"

partidas/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Avatar, Sistema, Dado, Base

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email"
        ]

class JuegoSearchForm(forms.Form):
    nombre = forms.CharField(max_length=50, required=False, label="Buscar juego")
    disponible = forms.BooleanField(required=False, label="Mostrar solo juegos disponibles")
    jugadores_minimos = forms.IntegerField(required=False, label="Jugadores mínimos")
    sistema = forms.ModelChoiceField(queryset=Sistema.objects.all(), required=False, label="Filtrar por sistema de juego")
    fecha = forms.DateField(required=False, label="Buscar por fecha", widget=forms.DateInput(attrs={'type': 'date'}))

class SistemaSearchForm(forms.Form):
    nombre = forms.CharField(max_length=50, required=False, label="Ingresar nombre del sistema")
    tipo_dado = [('', '---------')] + list(Dado.choices)
    tipo_base = [('', '---------')] + list(Base.choices)
    dado = forms.ChoiceField(choices=tipo_dado, required=False, label="Tipo de dado")
    base = forms.ChoiceField(choices=tipo_base, required=False, label="Base del sistema")

class AvatarCreateForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ["image"]

partidas/views.py
from .models import Juego, Reserva, Sistema, Avatar
from .forms import UserEditForm, JuegoSearchForm, SistemaSearchForm, AvatarCreateForm
from django import forms
from django.urls import reverse_lazy
from django.views.generic import(
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.

def home_view(request):
    return render(request, "partidas/home.html")

#CRUD SISTEMAS

class SistemaListView(LoginRequiredMixin, ListView):
    model = Sistema
    template_name = "partidas/vbc/sistema-list.html"
    context_object_name = "todos_los_sistemas"

class SistemaDetailView(LoginRequiredMixin, DetailView):
    model = Sistema
    template_name = "partidas/vbc/sistema-detail.html"
    context_object_name = "sistema"

class SistemaDeleteView(LoginRequiredMixin, DeleteView):
    model = Sistema
    template_name = "partidas/vbc/sistema-confirm-delete.html"
    success_url = reverse_lazy("sistema-list")

class SistemaUpdateView(LoginRequiredMixin, UpdateView):
    model = Sistema
    template_name = "partidas/vbc/sistema-form.html"
    fields = [
        "nombre",
        "dado",
        "base",
        "descripcion"
        ]
    context_object_name = "sistema"
    success_url = reverse_lazy("sistema-list")

class SistemaCreateView(LoginRequiredMixin, CreateView):
    model = Sistema
    template_name = "partidas/vbc/sistema-form.html"
    fields = [
        "nombre",
        "dado",
        "base",
        "descripcion"
        ] 
    success_url = reverse_lazy("sistema-list")

@login_required
def sistema_search_view(request):
    if request.method == "GET":
        form = SistemaSearchForm()
        return render(request, "partidas/vbc/sistema-form-search.html", context={"search_form": form})
    elif request.method == "POST":
        form = SistemaSearchForm(request.POST)
        if form.is_valid():
            nombre_de_sistema = form.cleaned_data["nombre"]
            tipo_dado = form.cleaned_data["dado"]
            tipo_base = form.cleaned_data["base"]

            sistemas_encontrados = Sistema.objects.filter(nombre__icontains=nombre_de_sistema)

            if tipo_dado:
                sistemas_encontrados = sistemas_encontrados.filter(dado = tipo_dado)

            if tipo_base:
                sistemas_encontrados = sistemas_encontrados.filter(base = tipo_base)

            contexto = {"todos_los_sistemas": sistemas_encontrados}
            return render(request, "partidas/vbc/sistema-list-search.html", contexto)
        else:
            return render(request, "partidas/vbc/sistema-form-search.html", context={"search_form": form})

#CRUD JUEGOS

class JuegoListView(LoginRequiredMixin, ListView):
    model = Juego
    template_name = "partidas/vbc/juego-list.html"
    context_object_name = "todos_los_juegos"

class JuegoDetailView(LoginRequiredMixin, DetailView):
    model = Juego
    template_name = "partidas/vbc/juego-detail.html"
    context_object_name = "juego"

class JuegoDeleteView(LoginRequiredMixin, DeleteView):
    model = Juego
    template_name = "partidas/vbc/juego-confirm-delete.html"
    success_url = reverse_lazy("juego-list")

class JuegoUpdateView(LoginRequiredMixin, UpdateView):
    model = Juego
    template_name = "partidas/vbc/juego-form.html"
    fields = [
        "nombre",
        "disponible",
        "numero_de_jugadores",
        "sistema_de_juego",
        "descripcion",
        "fecha",
        "hora_inicio",
        "hora_fin"
        ]
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['fecha'].widget = forms.DateInput(attrs={'type': 'date'})
        form.fields['hora_inicio'].widget = forms.TimeInput(attrs={'type': 'time', 'step': 60})
        form.fields['hora_fin'].widget = forms.TimeInput(attrs={'type': 'time', 'step': 60})
        return form

    context_object_name = "juego"
    success_url = reverse_lazy("juego-list")

class JuegoCreateView(LoginRequiredMixin, CreateView):
    model = Juego
    template_name = "partidas/vbc/juego-form.html"
    fields = [
        "nombre",
        "disponible",
        "numero_de_jugadores",
        "sistema_de_juego",
        "descripcion",
        "fecha",
        "hora_inicio",
        "hora_fin"
    ]
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['fecha'].widget = forms.DateInput(attrs={'type': 'date'})
        form.fields['hora_inicio'].widget = forms.TimeInput(attrs={'type': 'time', 'step': 60})
        form.fields['hora_fin'].widget = forms.TimeInput(attrs={'type': 'time', 'step': 60})
        return form
    
    success_url = reverse_lazy("juego-list")

@login_required
def juego_search_view(request):
    if request.method == "GET":
        form = JuegoSearchForm()
        return render(request, "partidas/vbc/juego-form-search.html", context={"search_form": form})
    elif request.method == "POST":
        form = JuegoSearchForm(request.POST)
        if form.is_valid():
            nombre_de_juego = form.cleaned_data["nombre"]
            solo_disponibles = form.cleaned_data["disponible"]
            jugadores_minimos = form.cleaned_data["jugadores_minimos"]
            sistema = form.cleaned_data["sistema"]
            fecha = form.cleaned_data["fecha"]

            juegos_encontrados = Juego.objects.filter(nombre__icontains=nombre_de_juego)

            if solo_disponibles:
                juegos_encontrados = juegos_encontrados.filter(disponible=True)

            if jugadores_minimos:
                juegos_encontrados = juegos_encontrados.filter(numero_de_jugadores__gte=jugadores_minimos)
            
            if sistema:
                juegos_encontrados = juegos_encontrados.filter(sistema_de_juego=sistema)
            
            if fecha:
                juegos_encontrados = juegos_encontrados.filter(fecha=fecha)

            contexto = {"todos_los_juegos": juegos_encontrados}
            return render(request, "partidas/vbc/juego-list-search.html", contexto)
        else:
            return render(request, "partidas/vbc/juego-form-search.html", context={"search_form": form})
        
#CRUD RESERVAS

class ReservaListView(LoginRequiredMixin, ListView):
    model = Reserva
    template_name = "partidas/vbc/reserva-list.html"
    context_object_name = "todas_las_reservas"

    def get_queryset(self):
        return Reserva.objects.filter(jugador=self.request.user)

class ReservaDetailView(LoginRequiredMixin, DetailView):
    model = Reserva
    template_name = "partidas/vbc/reserva-detail.html"
    context_object_name = "reserva"

class ReservaDeleteView(LoginRequiredMixin, DeleteView):
    model = Reserva
    template_name = "partidas/vbc/reserva-confirm-delete.html"
    success_url = reverse_lazy("reserva-list")

class ReservaUpdateView(LoginRequiredMixin, UpdateView):
    model = Reserva
    template_name = "partidas/vbc/reserva-form.html"
    fields = [
        "juego",
        "raza",
        "clase",
        "experiencia",
        "descripcion",
        ]
    context_object_name = "reserva"
    success_url = reverse_lazy("reserva-list")

    def form_valid(self, form):
        form.instance.jugador = self.request.user
        return super().form_valid(form)

class ReservaCreateView(LoginRequiredMixin, CreateView):
    model = Reserva
    template_name = "partidas/vbc/reserva-form.html"
    fields = [
        "juego",
        "raza",
        "clase",
        "experiencia",
        "descripcion",
        ]
    success_url = reverse_lazy("reserva-list")

    def form_valid(self, form):
        form.instance.jugador = self.request.user
        return super().form_valid(form)

# login / logout / Editar usuario / Crear Usuario

def user_login_view(request):
    if request.method == "GET":
        form = AuthenticationForm()
    elif request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.user_cache
            if user is not None:
                login(request, user)
                return redirect("home")
    
    return render(request, "partidas/login.html", {"ingresar": form})

def user_logout_view(request):
    logout(request)
    return redirect("login")

class UserUpdateView(UpdateView):
    model = User
    form_class = UserEditForm
    template_name = "partidas/user-edit-form.html"
    success_url = reverse_lazy("home")

    def get_object(self):
        return self.request.user

def user_creation_view(request):
    if request.method == "GET":
        form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    
    return render(request, "partidas/crear-usuario.html", {"form": form})

# Avatar para usuario

def avatar_view(request):
    if request.method == "GET":
        contexto = {"avatar": AvatarCreateForm()}
    else:
        form = AvatarCreateForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data["image"]
            avatar_existente = Avatar.objects.filter(user=request.user)
            avatar_existente.delete()
            nuevo_avatar = Avatar(image=image, user=request.user)
            nuevo_avatar.save()
            return redirect("home")
        else:
            contexto = {"avatar": form}

    return render(request, "partidas/avatar-create.html", context=contexto)

# About

def about_view(request):
    return render(request, "partidas/about.html")

partidas/templates/partidas/vbc/juego-confirm-delete.html
{% extends 'partidas/base.html' %}

{% block title %}Confirmar{% endblock %}

{% block content %}


<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p>Seguro que quieres borrar "{{ object.nombre }}"?</p>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Borrar">
                            <a href="{% url 'juego-list' %}">Cancelar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/juego-detail.html
{% extends 'partidas/base.html' %}

{% block title %}Detalle del Juego{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="text-right mb-3">
                    <a href="#" class="btn btn-primary" onclick="history.back()">Volver</a>
                </div>
                <div class="card shadow-sm">
                    <div class="card-header">
                        Detalle del Juego
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ juego.nombre }}</h5>
                        {% if juego.disponible %}
                        <h6 class="card-subtitle mb-2">Disponible</h6>
                        {% else %}
                        <h6 class="card-subtitle mb-2 text-danger">No Disponible</h6>
                        {% endif %}
                        <p class="card-text">Juego para {{ juego.numero_de_jugadores }} jugadores</p>
                        <p class="card-text">Sistema de juego: {{ juego.sistema_de_juego }}</p>
                        <p class="card-text">Descripción: {{ juego.descripcion | default:"No proporcionado" }}</p>
                        <p class="card-text">Fecha: {{ juego.fecha | date:"d/m/Y" }}</p>
                        <p class="card-text">Hora de inicio: {{ juego.hora_inicio | time:"H:i" }}</p>
                        <p class="card-text">Hora de fin: {{ juego.hora_fin | time:"H:i" }}</p>
                    </div>
                </div>
                <div class="mt-4">
                    <h3>Jugadores en esta partida</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Nombre de Jugador</th>
                                <th scope="col">Raza</th>
                                <th scope="col">Clase</th>
                                <th scope="col">Experiencia</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for reserva in juego.reservas.all %}
                            <tr>
                                <td>
                                    {% if reserva.jugador.avatar %}
                                        <img src="{{ reserva.jugador.avatar.image.url }}" alt="Avatar" style="height: 40px; width: 40px; border-radius: 50%;">
                                    {% endif %}
                                </td>
                                <td>{{ reserva.jugador }}</td>
                                <td>{{ reserva.raza }}</td>
                                <td>{{ reserva.clase }}</td>
                                <td>{{ reserva.get_experiencia_display }}</td>
                                <td class="d-flex align-items-center">
                                    <a href="{% url 'reserva-detail' reserva.id %}" class="btn btn-primary btn-sm mr-1">Ver</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5">No hay jugadores para esta partida.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/juego-form-search.html
{% extends 'partidas/base.html' %}

{% block title %}Buscar Juego{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="card shadow-sm">
                    <div class="card-header">
                        Filtros de búsqueda
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ search_form.as_p }}
                            <button type="submit" class="btn btn-primary">Buscar</button>
                            <a href="#" class="btn btn-primary mr-2" onclick="history.back()">Volver</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/juego-form.html
{% extends 'partidas/base.html' %}

{% block title %} Listado de Juegos {% endblock %}

{% block content %}
<h3>{% if object %}Editar Juego: {{ object.nombre }}{% else %}Crear Juego{% endif %}</h3>
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="card shadow-sm">
                        <div class="card-header">
                            Datos del Juego
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">Enviar</button>
                                <a href="{% url 'juego-list' %}">Cancelar</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

partidas/templates/partidas/vbc/juego-list-search.html
{% extends 'partidas/base.html' %}

{% block title %} Listado de Partidas {% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
                <h2 class="mb-0">Partidas</h2>
            </div>
            <div>
                <a href="{% url 'juego-list' %}" class="btn btn-primary">Todos los Juegos</a>
                <a href="{% url 'juego-search' %}" class="btn btn-primary">Buscar Juego</a>
                <a href="{% url 'juego-create' %}" class="btn btn-success mr-2">Crear Juego</a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Partida</th>
                    <th scope="col">Disponible</th>
                    <th scope="col">Sistema de Juego</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Hora de Inicio</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% if todos_los_juegos %}
                {% for juego in todos_los_juegos %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ juego.nombre }}</td>
                    {% if juego.disponible %}
                        <td>Si</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                    <td>{{ juego.sistema_de_juego }}</td>
                    <td>{{ juego.fecha|date:"d/m/Y" }}</td>
                    <td>{{ juego.hora_inicio|time:"H:i" }}</td>
                    <td>
                        <a href="{% url 'juego-detail' juego.id %}" class="btn btn-primary btn-sm">Ver</a>
                        <a href="{% url 'juego-update' juego.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'juego-delete' juego.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                    {% endfor %}
                </tr>
                {% else %}
                <tr>
                    <td colspan="7">No hay Partidas disponibles.</td>
                </tr>
                {% endif %}

            </tbody>
        </table>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/reserva-confirm-delete.html
{% extends 'partidas/base.html' %}

{% block title %}Confirmar{% endblock %}

{% block content %}


<section class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <div class="card shadow-sm">
                    <div class="card-header">
                        <p>¿Seguro que quieres borrar la reserva?</p>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger" value="Borrar">
                            <a href="{% url 'reserva-list' %}">Cancelar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/sistema-list-search.html
{% extends 'partidas/base.html' %}

{% block title %} Listado de Sistemas {% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
                <h2 class="mb-0">Sistemas</h2>
            </div>
            <div>
                <a href="{% url 'sistema-list' %}" class="btn btn-primary">Todos los Sistemas</a>
                <a href="{% url 'sistema-search' %}" class="btn btn-primary">Buscar Sistema</a>
                <a href="{% url 'sistema-create' %}" class="btn btn-success mr-2">Crear Sistema</a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Sistema</th>
                    <th scope="col">Tipo de dado</th>
                    <th scope="col">Base del juego</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% if todos_los_sistemas %}
                {% for sistema in todos_los_sistemas %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ sistema.nombre }}</td>
                    <td>{{ sistema.get_dado_display }}</td>
                    <td>{{ sistema.get_base_display }}</td>
                    <td>
                        <a href="{% url 'sistema-detail' sistema.id %}" class="btn btn-primary btn-sm">Ver</a>
                        <a href="{% url 'sistema-update' sistema.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'sistema-delete' sistema.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                    {% endfor %}
                </tr>
                {% else %}
                <tr>
                    <td colspan="7">No hay Sistemas disponibles.</td>
                </tr>
                {% endif %}

            </tbody>
        </table>
    </div>
</section>
{% endblock %}

partidas/templates/partidas/vbc/sistema-list.html
{% extends 'partidas/base.html' %}

{% block title %} Listado de Sistemas {% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
                <h2 class="mb-0">Sistemas</h2>
            </div>
            <div>
                <a href="{% url 'sistema-search' %}" class="btn btn-primary">Buscar Sistema</a>
                <a href="{% url 'sistema-create' %}" class="btn btn-success mr-2">Crear Sistema</a>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Sistema</th>
                    <th scope="col">Tipo de dado</th>
                    <th scope="col">Base del juego</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% if todos_los_sistemas %}
                {% for sistema in todos_los_sistemas %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ sistema.nombre }}</td>
                    <td>{{ sistema.get_dado_display }}</td>
                    <td>{{ sistema.get_base_display }}</td>
                    <td>
                        <a href="{% url 'sistema-detail' sistema.id %}" class="btn btn-primary btn-sm">Ver</a>
                        <a href="{% url 'sistema-update' sistema.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'sistema-delete' sistema.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                    {% endfor %}
                </tr>
                {% else %}
                <tr>
                    <td colspan="7">No hay Sistemas disponibles.</td>
                </tr>
                {% endif %}

            </tbody>
        </table>
    </div>
</section>
{% endblock %}